//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class changeStatusMessages
    {
        public int id { get; set; }
        public string oldStatus { get; set; }
        public string newStatus { get; set; }
        public string requestID { get; set; }
        public string timepoint { get; set; }
    
        public virtual requests requests { get; set; }
    }
}
