//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public string commentID { get; set; }
        public string message { get; set; }
        public string masterID { get; set; }
        public string requestID { get; set; }
    
        public virtual users users { get; set; }
        public virtual requests requests { get; set; }
    }
}
