//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarServiceDBEntities1 : DbContext
    {

        static CarServiceDBEntities1 _context; 
        public CarServiceDBEntities1()
            : base("name=CarServiceDBEntities1")
        {
        }

        public static CarServiceDBEntities1 getContext()
        {
            if (_context == null)
            {
                _context = new CarServiceDBEntities1();
            }

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<changeStatusMessages> changeStatusMessages { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<mastersReports> mastersReports { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
