//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requests()
        {
            this.changeStatusMessages = new HashSet<changeStatusMessages>();
            this.comments = new HashSet<comments>();
            this.mastersReports = new HashSet<mastersReports>();
        }
    
        public string requestID { get; set; }
        public string startDate { get; set; }
        public string carType { get; set; }
        public string carModel { get; set; }
        public string problemDescryption { get; set; }
        public string requestStatus { get; set; }
        public string completionDate { get; set; }
        public string repairParts { get; set; }
        public string masterID { get; set; }
        public string clientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<changeStatusMessages> changeStatusMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mastersReports> mastersReports { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
